apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mwzumao96-python 
  janus-idp.io/tekton: mwzumao96-python
  backstage.io/kubernetes-id: mwzumao96-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mwzumao96-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  