apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: mwzumao96-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:7461c396edcdea033ddc5e4a6f2332eb143cda65@sha256:d3c224a47bf5331430a0e2bead3ff45d90b8e88118dfb3240e0b264f26e9e4d6
          name: container-image
